title: Lizee Status
baseURL: https://status.lizee.io
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: e-commerce frontend
      description: ""
      link: ""
      group: Rental
    - name: e-commerce API & Admin
      description: ""
      link: ""
      group: Rental
    - group: Logistic
      name: Logistic API
    - name: Logistic App
      group: Logistic
    - name: Data API
      group: Data
    - name: Data App
      group: Data
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: Europe/Paris
  logo: static/images/uploads/lizee1.png
  description_header: Get more info about us at <a class='text-grey-darkest'
    title='Visit lizee.co' href='https://lizee.co/'>lizee.co</a>.<br />Follow us
    <a class='text-grey-darkest' title='Visit our page on Linkedin'
    href='https://www.linkedin.com/company/lizee-sas/'>on Linkedin</a> or
    subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be
    alerted of new events.
  copyrightHolder: © Copyright Loop Logistics S.A.S. 2021
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Rental
    - Logistic
    - Data
  icon: /images/clearstatus.png
  description_footer: Get more info about us at <a class='text-grey-darkest'
    title='Visit lizee.co' href='https://lizee.co/'>lizee.co</a>
